import requests

catagories = [
              "milk",
              "butter",
              "carrots",
              "parsnip",
              "Raspberries",
              "bananas",
              "wine",
              "porridge",
              "cereal",
              "mandarins",
              "Mushrooms",
              "Broccoli",
              "Potato",
              "Apple",
              "Orange",
              "Cabbage",
              "beans",
              "Cucumber",
              "Celery",
              "Pear",
              "Eggs",
              "Blueberry",
              "Spinach",
              "beetroot",
              "garlic",
              "pepper",
              "olive oil",
              "tofu",
              "vinegar",
              "lemon",
              "lime",
              "onion",
              "Kale",
              "Grape",
              "Pepper",
              "Tomato",
              "avocado",
              "noodles",
              "bread",
              "Dog food",
              "Sugar",
              "Cola",
              "Fanta",
              "Lemonade",
              "Crisps",
              "Nuts",
              "Nachos",
              "Cadbury",
              "Chocolate",
              "Avonmore",
              "Lucozade",
              "Tayto",
              "7 up",
              "Jacobs",
              "Goodfellas",
              "Monster",
              "Nescafe",
              "Red Bull",
              "Pringles",
              "Ballygowan",
              "Dairygold",
              "Kinder",
              "Yoplait",
              "McVities",
              "Club",
              "chickpea",
              "pasta"]

for item in catagories:
    print(requests.get(f"https://www.taifuwiddies.net:8000/products/{item}"))